server:
  port: 8887
  tomcat:
    uri-encoding: UTF-8
    max-connections: 2000
    accept-count: 100
    threads:
      max: 600
      min-spare: 30
    accesslog:
      enabled: true
      directory: ${logging.file.path}
      pattern: "%h %l %u %t %r %s %b %D"


management:
  server:
    port: 2${server.port}
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      lettuce: false
    distribution:
      expiry:
        "[http.server.requests]": 10s
        "[http.client.requests]": 10s
      percentiles:
        "http.server.requests": 0.95, 0.99
        "http.client.requests": 0.95, 0.99
