# 配置中心配置
server:
  port: 8866
  reactive:
    session:
      timeout: 30m
  compression:
    enabled: true
  shutdown:
    graceful: true

spring:
  cloud:
    nacos:
      discovery:
        watch-delay: 3000
    loadbalancer:
      cache:
        ttl: 3s
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 3${server.port}
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 3s
      loadbalancer:
        use404: true
      routes:
        - id: route-consumer
          uri: lb://consumer
          predicates:
            - Method=GET
        - id: route-provider
          uri: lb://provider
          predicates:
            - Method=POST

management:
  server:
    port: 2${server.port}
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true