# 配置中心配置
server:
  port: 8866
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30



spring:
  cloud:
    loadbalancer:
      cache:
        ttl: 5s
    sentinel:
      transport:
        dashboard: 127.0.0.1:8849
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 3s
      loadbalancer:
        use404: true
      routes:
        - id: route-consumer
          uri: lb://consumer
          predicates:
            - Method=GET
        - id: route-provider
          uri: lb://provider
          predicates:
          - Method=POST

